config/routes.rb
Rails.application.routes.draw do
  root to: 'plans#new'

  resources :plans, except: [:index, :edit, :update] do
    get 'email', on: :member
  end

  resources :readings, only: [] do
    get 'complete', on: :member
  end
end

app/models/reading.rb
class Reading < ApplicationRecord
  belongs_to :plan

  def self.create_for(plan, chapter:)
    create(plan: plan, book_name: plan.book_name, chapter: chapter)
  end

  def text
    passage = fetch_passage
    passage["search"]["result"]["passages"]["passage"]["text"]
  end

  def title
    "#{book_name} Chapter #{chapter}"
  end

  def copyright
    passage = fetch_passage
    passage["search"]["result"]["passages"]["passage"]["copyright"]
  end

  def mark_complete
    update!(completed_at: DateTime.now)
  end

  def book
    Book.get(book_name)
  end

  def completed?
    completed_at.present?
  end

  def mark_as_sent
    now = DateTime.now
    attrs = { last_sent_at: now }
    attrs.merge!({ first_sent_at: now }) unless sent?

    update(attrs)
  end

  def sent?
    last_sent_at.present?
  end

  private

  def fetch_passage
    reading = "#{book_name}+#{chapter}"
    @bible_api_response ||= BibleApi.fetch("https://bibles.org/v2/passages.xml?q[]=#{reading}&version=eng-GNTD")
  end
end

app/controllers/readings_controller.rb
class ReadingsController < ApplicationController
  def complete
    @reading = Reading.find(reading_id)
    @plan = @reading.plan

    if @reading.completed?
      render :already_completed
    else
      @plan.complete_reading(@reading)

      ReadingMailer.send_reading(@plan).deliver unless @plan.completed?
      @reading.mark_as_sent
    end
  end

  private

  def reading_id
    params.require(:id)
  end

end

app/helpers/readings_helper.rb
module ReadingsHelper
end

app/views/readings/already_completed.html.erb
<% if @plan.completed? %>
  <p>
    You are now done reading <%= @plan.book_name %>. Please choose another
    book to read.
  </p>

  <p>
    <%= link_to "Choose a New Book", new_plan_path %>
  </p>
<% else %>
  <p>
    You have already completed reading chapter <%= @reading.chapter %> of
    <%= @reading.book_name %>.
  </p>

  <p><%= link_to "Resend the next reading", email_plan_path(@plan) %></p>
<% end %>

app/views/readings/complete.html.erb
<p>
  You have completed reading chapter <%= @reading.chapter %> of
  <%= @reading.book_name %>.
</p>

<% if @plan.completed? %>
  <p>
    You are now done reading <%= @plan.book_name %>. Please choose another
    book to read.
  </p>

  <p>
    <%= link_to  %>
  </p>
<% else %>
  <p>
    We have send you the next chapter to read when you are ready.
  </p>
<% end %>