config/routes.rb
Rails.application.routes.draw do
  root to: 'plans#new'

  resources :plans, except: [:index, :edit, :update] do
    get 'email', on: :member
  end

  resources :readings, only: [] do
    get 'complete', on: :member
  end
end

app/models/plan.rb
class Plan < ApplicationRecord
  belongs_to :user
  has_many :readings, ->{ order(:created_at) }, dependent: :destroy

  def self.active_for(user)
    find_by(user: user, completed_at: nil)
  end

  def active?
    completed_at.nil?
  end

  def mark_complete
    update!(completed_at: DateTime.now)
  end

  def start_reading
    return if started?

    Reading.create_for(self, chapter: 1)
  end

  def current_reading
    readings.find_by(completed_at: nil)
  end

  def complete_reading(reading)
    return if completed? || reading.completed?

    chapter = reading.chapter
    book = reading.book

    reading.mark_complete

    if chapter >= book.chapters
      mark_complete
    else
      Reading.create_for(self, chapter: chapter + 1)
    end
  end

  def started?
    readings.present?
  end

  def completed?
    completed_at.present?
  end
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  before_action :active_plan

  def new
    redirect_to plan_path(active_plan) if active_plan

    @books = Book.all
  end

  def create
    if active_plan.nil?
      @new_plan = Plan.create(book_name: book_name, user: current_user)
      @new_plan.start_reading

      ReadingMailer.send_reading(@new_plan).deliver
    end
  end

  def show
    @plan = Plan.find(plan_id)
  end

  def destroy
    @plan = Plan.find(plan_id)

    @plan.mark_complete if @plan.active?

    redirect_to new_plan_path
  end

  def email
    @plan = Plan.find(plan_id)

    ReadingMailer.send_reading(@plan).deliver
  end

  private

  def plan_id
    params.require(:id)
  end

  def book_name
    params.require(:book)
  end

  def force_new_plan
    params[:force_new_plan]
  end

  def active_plan
    @active_plan ||= Plan.active_for(current_user)
  end
end

app/views/plans/_book.html.erb
<%= link_to book.name, plans_path(book: book.name), method: :post %>

app/views/plans/create.html.erb
<% if @active_plan %>
  You are already reading <%= @active_plan.book_name %>.
<% else %>
  We just sent you an email with your first reading from <%= @new_plan.book_name %>
<% end %>

app/views/plans/email.html.erb
<p>
  We just sent you your next reading from <%= @plan.book_name %>
</p>

app/views/plans/new.html.erb
<%= render collection: @books, partial: 'book' %>

app/views/plans/show.html.erb
<% if @plan.completed? %>
  <p>You have already completed reading <%= @plan.book_name %>.</p>

  <p><%= link_to "Choose a New Book", new_plan_path %></p>
<% else %>
  <p>You are currently reading <%= @plan.book_name %>.</p>

  <p>Would like to mark this reading as complete and choose a new book?</p>

  <p><%= link_to "Choose a New Book", plan_path(@active_plan), method: :delete %></p>

  <p><%= link_to "Resend Latest Reading", email_plan_path(@active_plan) %></p>
<% end %>